package entity;
// Generated 31/05/2018 09:05:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GenerarHistorial generated by hbm2java
 */
public class GenerarHistorial  implements java.io.Serializable {


     private GenerarHistorialId id;
     private Historial historial;
     private Medico medico;
     private Date fechaGenerar;

    public GenerarHistorial() {
    }

    public GenerarHistorial(GenerarHistorialId id, Historial historial, Medico medico, Date fechaGenerar) {
       this.id = id;
       this.historial = historial;
       this.medico = medico;
       this.fechaGenerar = fechaGenerar;
    }
   
    public GenerarHistorialId getId() {
        return this.id;
    }
    
    public void setId(GenerarHistorialId id) {
        this.id = id;
    }
    public Historial getHistorial() {
        return this.historial;
    }
    
    public void setHistorial(Historial historial) {
        this.historial = historial;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public Date getFechaGenerar() {
        return this.fechaGenerar;
    }
    
    public void setFechaGenerar(Date fechaGenerar) {
        this.fechaGenerar = fechaGenerar;
    }




}


