package entity;
// Generated 31/05/2018 09:05:04 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico implements java.io.Serializable {

    private String curpm;
    private Administrador administrador;
    private String nombre;
    private String appat;
    private String apmat;
    private int edad;
    private String correo;
    private String telefono;
    private String contrasena;
    private String especialidad;
    private int consultorio;
    private Date fechaAsignar;
    private Set solicitarCitas = new HashSet(0);
    private Set generarHistorials = new HashSet(0);
    private boolean editable;

    public Medico() {
    }

    public Medico(String curpm, Administrador administrador, String nombre, String appat, String apmat, int edad, String correo, String telefono, String contrasena, String especialidad, int consultorio, Date fechaAsignar) {
        this.curpm = curpm;
        this.administrador = administrador;
        this.nombre = nombre;
        this.appat = appat;
        this.apmat = apmat;
        this.edad = edad;
        this.correo = correo;
        this.telefono = telefono;
        this.contrasena = contrasena;
        this.especialidad = especialidad;
        this.consultorio = consultorio;
        this.fechaAsignar = fechaAsignar;
    }

    public Medico(String curpm, Administrador administrador, String nombre, String appat, String apmat, int edad, String correo, String telefono, String contrasena, String especialidad, int consultorio, Date fechaAsignar, Set solicitarCitas, Set generarHistorials) {
        this.curpm = curpm;
        this.administrador = administrador;
        this.nombre = nombre;
        this.appat = appat;
        this.apmat = apmat;
        this.edad = edad;
        this.correo = correo;
        this.telefono = telefono;
        this.contrasena = contrasena;
        this.especialidad = especialidad;
        this.consultorio = consultorio;
        this.fechaAsignar = fechaAsignar;
        this.solicitarCitas = solicitarCitas;
        this.generarHistorials = generarHistorials;
    }

    public String getCurpm() {
        return this.curpm;
    }

    public void setCurpm(String curpm) {
        this.curpm = curpm;
    }

    public Administrador getAdministrador() {
        return this.administrador;
    }

    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getAppat() {
        return this.appat;
    }

    public void setAppat(String appat) {
        this.appat = appat;
    }

    public String getApmat() {
        return this.apmat;
    }

    public void setApmat(String apmat) {
        this.apmat = apmat;
    }

    public int getEdad() {
        return this.edad;
    }

    public void setEdad(int edad) {
        this.edad = edad;
    }

    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getContrasena() {
        return this.contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    public String getEspecialidad() {
        return this.especialidad;
    }

    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }

    public int getConsultorio() {
        return this.consultorio;
    }

    public void setConsultorio(int consultorio) {
        this.consultorio = consultorio;
    }

    public Date getFechaAsignar() {
        return this.fechaAsignar;
    }

    public void setFechaAsignar(Date fechaAsignar) {
        this.fechaAsignar = fechaAsignar;
    }

    public Set getSolicitarCitas() {
        return this.solicitarCitas;
    }

    public void setSolicitarCitas(Set solicitarCitas) {
        this.solicitarCitas = solicitarCitas;
    }

    public Set getGenerarHistorials() {
        return this.generarHistorials;
    }

    public void setGenerarHistorials(Set generarHistorials) {
        this.generarHistorials = generarHistorials;
    }

    public boolean isEditable() {
        return editable;
    }

    public void setEditable(boolean editable) {
        this.editable = editable;
    }

}
