package entity;
// Generated 31/05/2018 09:05:04 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private String curpp;
     private String nombre;
     private String appat;
     private String apmat;
     private int edad;
     private String correo;
     private String telefono;
     private String contrasena;
     private String enfermedad;
     private Date cita;
     private Set solicitarCitas = new HashSet(0);
     private Historial historial;

    public Paciente() {
    }

	
    public Paciente(String curpp, String nombre, String appat, String apmat, int edad, String correo, String telefono, String contrasena, String enfermedad, Date cita) {
        this.curpp = curpp;
        this.nombre = nombre;
        this.appat = appat;
        this.apmat = apmat;
        this.edad = edad;
        this.correo = correo;
        this.telefono = telefono;
        this.contrasena = contrasena;
        this.enfermedad = enfermedad;
        this.cita = cita;
    }
    public Paciente(String curpp, String nombre, String appat, String apmat, int edad, String correo, String telefono, String contrasena, String enfermedad, Date cita, Set solicitarCitas, Historial historial) {
       this.curpp = curpp;
       this.nombre = nombre;
       this.appat = appat;
       this.apmat = apmat;
       this.edad = edad;
       this.correo = correo;
       this.telefono = telefono;
       this.contrasena = contrasena;
       this.enfermedad = enfermedad;
       this.cita = cita;
       this.solicitarCitas = solicitarCitas;
       this.historial = historial;
    }
   
    public String getCurpp() {
        return this.curpp;
    }
    
    public void setCurpp(String curpp) {
        this.curpp = curpp;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAppat() {
        return this.appat;
    }
    
    public void setAppat(String appat) {
        this.appat = appat;
    }
    public String getApmat() {
        return this.apmat;
    }
    
    public void setApmat(String apmat) {
        this.apmat = apmat;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(String enfermedad) {
        this.enfermedad = enfermedad;
    }
    public Date getCita() {
        return this.cita;
    }
    
    public void setCita(Date cita) {
        this.cita = cita;
    }
    public Set getSolicitarCitas() {
        return this.solicitarCitas;
    }
    
    public void setSolicitarCitas(Set solicitarCitas) {
        this.solicitarCitas = solicitarCitas;
    }
    public Historial getHistorial() {
        return this.historial;
    }
    
    public void setHistorial(Historial historial) {
        this.historial = historial;
    }




}


