package entity;
// Generated 31/05/2018 09:05:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SolicitarCita generated by hbm2java
 */
public class SolicitarCita  implements java.io.Serializable {


     private SolicitarCitaId id;
     private Medico medico;
     private Paciente paciente;
     private Date fechaCita;
     private int consultorio;
     private String indicaciones;

    public SolicitarCita() {
    }

    public SolicitarCita(SolicitarCitaId id, Medico medico, Paciente paciente, Date fechaCita, int consultorio, String indicaciones) {
       this.id = id;
       this.medico = medico;
       this.paciente = paciente;
       this.fechaCita = fechaCita;
       this.consultorio = consultorio;
       this.indicaciones = indicaciones;
    }
   
    public SolicitarCitaId getId() {
        return this.id;
    }
    
    public void setId(SolicitarCitaId id) {
        this.id = id;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getFechaCita() {
        return this.fechaCita;
    }
    
    public void setFechaCita(Date fechaCita) {
        this.fechaCita = fechaCita;
    }
    public int getConsultorio() {
        return this.consultorio;
    }
    
    public void setConsultorio(int consultorio) {
        this.consultorio = consultorio;
    }
    public String getIndicaciones() {
        return this.indicaciones;
    }
    
    public void setIndicaciones(String indicaciones) {
        this.indicaciones = indicaciones;
    }




}


